model_opts:
  name: "Unet"
  args:
    inchannels: 3
    outchannels: 1
    net_depth: 4
    
train_par:
  gpu_to_use: 'cuda:1' # 'cuda:1', select the GPU where you want your training. if 'default' it will use torch.device("cuda" if torch.cuda.is_available() else "cpu")
  random_seed: 'default'
  epochs: 60
  batch_size: 4
  workers: 4
  lr: 0.01
  eval_threshold: 0.5
  patience: 15
  early_stopping_flag: True
  results_path: "results/256x256"
  optimizer:
    name: 'Adadelta'
  loss_opts:
    name: 'BCEDiceLoss'
    args:
      weight: 0.5 # this is for BCELogits (value will be computed automatically) & BCEDiceLoss (you need to input a value, default: 0.1)
      alpha: 1 # this is only for focal loss
      gamma: 2 # this is only for focal loss

dataset:
  experiment: "exp_MICCAI"
  data_dir: "../dataset/256x256"
  train: "data/experiment_002/train_02_cv_01.csv"
  dev: "data/experiment_002/dev_02_cv_01.csv"
  test: "data/experiment_002/test_02.csv"
  normalization: "macenko"
  cache_data: True
  rescale_factor: 256
